// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '@/components/ThemeRegistry';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Portal Lab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 1. Adicione um fundo cinza claro ao body */}
      <body className={`${inter.className} bg-gray-50`}>
        <ThemeRegistry>
          <Box className="flex flex-col min-h-screen">
            <Header />
            {/* 2. O main deve crescer para ocupar o espaço */}
            <Box component="main" className="flex-grow">
              {/* 3. ESTE É O CONTAINER QUE CENTRALIZA TUDO */}
              <div className="container mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
                {children}
              </div>
            </Box>
            <Footer />
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}