// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '@/components/ThemeRegistry';
import { Header } from '@/components/layout/Header'; // 1. Importe o Header
import { Footer } from '@/components/layout/Footer'; // 2. Importe o Footer
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Portal Lab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry>
          {/* 3. Estruture a página para o footer ficar no final */}
          <Box className="flex flex-col min-h-screen">
            <Header />
            {/* O conteúdo principal da página (children) */}
            <Box component="main" className="flex-grow">
              {children}
            </Box>
            <Footer />
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}